---
title: "agData"
author: "Derek Michael Wright <derek.wright@usask.ca>"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = T)
```

## Instalation

Use the following code to install the `agdata` package in R

```{r eval = F}
devtools::install_github("derekmichaelwright/agData")
```

```{r echo = F}
library(agData)

```

## Datasets

The agData package contains agriculture related data sets for quick access using R:

```{r, eval = F}
?agData_FAO_Crops
?agData_FAO_Livestock
?agData_USDA_Crops
?agData_STATCAN_Crops
?agData_STATCAN_Livestock
?agData_STATCAN_Beehives
```

## Explore Data

```{r warning = F, message = F}
# Load libraries
library(agData)
library(tidyverse)
```

```{r}
# Load data
xx <- agData_FAO_Crops %>% as.tibble()
xx
# List measurements
xx %>% distinct(Measurement)
# List areas
xx %>% distinct(Area)
# List crops
xx %>% distinct(Crop)
# Spread data to wide format
xx %>% 
  unite(Measurement, Measurement, Unit) %>%
  spread(Measurement, Value)
```

## A Quick Example

```{r fig.width = 10, fig.height = 4}
# Filter data for ploting
xx <- xx %>% 
  filter(Area == "Canada", 
         Crop == "Lentils", 
         Measurement == "Production")
# Plot
ggplot(xx, aes(x = Year, y = Value / 1000000)) + 
  geom_line() +
  labs(title = "Lentil Production", 
       y = "million tonnes",
       x = NULL)
```

